server:
  port: 8091

spring:
  kafka:
    consumer:
      group-id: general-publish-group
    producer:
      bootstrap-servers: 127.0.0.1:9092

sql:
  read-partyUid: SELECT ROW_ID,PARTY_UID as GUID from SIEBEL.S_PARTY where party_uid <>row_id and party_type_cd ='Person'
  primary-data: SELECT b.PR_NAME_ID,b.PR_IDENTITY_ID,PR_AFFL_ID,PR_PER_ADDR_ID,PR_EMAIL_ADDR_ID,PR_ALT_PH_NUM_ID,FST_NAME,LAST_NAME,BIRTH_DT,EMAIL_ADDR,MID_NAME,HOME_PH_NUM,SEX_MF,SOC_SECURITY_NUM,DEATH_DT,JOB_TITLE,MARITAL_STAT_CD,PLACE_OF_BIRTH,PLACE_OF_DEATH,MARITAl_STAT_DT,PER_TITLE_SUFFIX,DEGREE from SIEBEL.S_CONTACT a,SIEBEL.S_CONTACT_UCMX b where a.row_id=b.PAR_ROW_ID and a.row_id=?
  source-data: Select CIF_EXT_SYST_ID,EXT_CUST_ID1 from SIEBEL.s_cif_con_map where con_id =?
  email-data: SELECT ROW_ID,ADDR,X_LOG_DEL_FLG,NAME from SIEBEL.S_PER_COMM_ADDR WHERE COMM_MEDIUM_CD ='Email' AND PER_ID=?
  phone-data: SELECT ROW_ID,ADDR,X_LOG_DEL_FLG,NAME from SIEBEL.S_PER_COMM_ADDR WHERE COMM_MEDIUM_CD ='Phone' AND PER_ID=?
  address-data: Select a.ADDR_NAME,a.ADDR_LINE_2,a.STATE,a.CITY,a.COUNTRY,a.ZIPCODE,b.ACTIVE_FLG,b.RELATION_TYPE_CD,b.START_DT from SIEBEL.S_ADDR_PER a,SIEBEL.S_con_addr b where b.ADDR_PER_ID=a.row_id and b.contact_id=?
  nid-data: SELECT ROW_ID,TYPE_CD,IDENTITY_DOC_NUM,EFF_START_DT,ISS_COUNTRY_CD,X_LOG_DEL_FLG FROM SIEBEL.S_CON_IDNTY_DOC WHERE contact_id =?
  affiliation-data: select ROW_ID,PARTY_ID,REL_TYPE_CD,AFFL_RANK, AFFL_STATUS_CD, AFFL_STATUS_DESC ,START_DT,END_DT from siebel.S_PARTY_REL where PARTY_ID=?
  name-data: select ROW_ID,EFF_END_DT,EFF_START_DT,FST_NAME,FULL_NAME,LAST_NAME,X_LOG_DEL_FLG,PER_TITLE,MID_NAME,TYPE_CD,PREF_FST_NAME,X_REC_ACTIVE_FLG,ROYAL_PREFIX,ROYAL_SUFFIX,SECOND_LAST_NAME,PER_TITLE_SUFFIX from siebel.S_CONTACT_NAME WHERE contact_id =?

